name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup NPM and Install Dependencies
        uses: ./.github/actions/setup-npm
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@torian12321'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ§ª Run tests
        run: npm run test

      - name: ğŸ’… Check formatting
        run: npm run format:check

      - name: ğŸ“ Check builds
        run: |
          npm run build &
          npm run build:docs &
          wait
